const members = [
  {
    id: '26001',
    name: '김구현',
    company: '케이알산업',
    position: '상무',
    memberType: '정회원',
    field: '시공',
    department: '개발분과',
    phone: '010-9401-8700',
    email: 'kimkh@krindus.co.kr',
    intro: '',
  },
  {
    id: '26002',
    name: '김기현',
    company: '코람코자산신탁',
    position: '이사',
    memberType: '정회원',
    field: '금융',
    department: '융합분과',
    phone: '010-8591-3971',
    email: 'escoba@hanmail.net',
    intro: '',
  },
  {
    id: '26003',
    name: '김선철',
    company: '㈜나산종합건축사사무소',
    position: '사장',
    memberType: '',
    field: '설계/감리',
    department: '도시분과',
    phone: '010-2319-8502',
    email: 'sunchal2001@hanmail.net',
    intro: '',
  },
  {
    id: '26004',
    name: '김세훈',
    company: '㈜케이에스에이치파트너스',
    position: '대표이사',
    memberType: '',
    field: '시행',
    department: '도시분과',
    phone: '010-5100-4967',
    email: 'sehun.kim@newnnext.com',
    intro: '',
  },
  {
    id: '26005',
    name: '김승진',
    company: '미래에셋증권',
    position: '이사',
    memberType: '준회원',
    field: '금융',
    department: '창조분과',
    phone: '010-7760-0509',
    email: 'seungjin.kim@miraeasset.com',
    intro: '',
  },
  {
    id: '26006',
    name: '김시찬',
    company: '성원엔지니어링',
    position: '부사장',
    memberType: '',
    field: '전문건설',
    department: '도시분과',
    phone: '010-5410-0637',
    email: 'artchan1234@naver.com',
    intro: '',
  },
  {
    id: '26007',
    name: '김영미',
    company: '수협은행',
    position: '지점장',
    memberType: '',
    field: '금융',
    department: '개발분과',
    phone: '010-6396-2717',
    email: 'kimseller@suhyup-bank.com',
    intro: '',
  },
  {
    id: '26008',
    name: '김영철',
    company: '바인그룹 (동화세상에듀코)',
    position: '회장',
    memberType: '준회원',
    field: '시행',
    department: '도시분과',
    phone: '010-5239-4542',
    email: 'educo@educo.co.kr',
    intro: '',
  },
  {
    id: '26009',
    name: '김인식',
    company: '한국투자부동산신탁',
    position: '상무보',
    memberType: '정회원',
    field: '금융',
    department: '도시분과',
    phone: '010-9250-3743',
    email: 'nkis0208@naver.com',
    intro: '',
  },
  {
    id: '26010',
    name: '김재구',
    company: '데이터노우즈',
    position: '사장',
    memberType: '준회원',
    field: '분양대행',
    department: '개발분과',
    phone: '010-9351-6355',
    email: 'theanswer@dataknows.ai',
    intro: '',
  },
  {
    id: '26011',
    name: '김재만',
    company: '㈜에스피에스테크',
    position: '대표이사',
    memberType: '',
    field: '설계/감리',
    department: '융합분과',
    phone: '010-6334-0232',
    email: 'nakjman@naver.com',
    intro: '',
  },
  {
    id: '26012',
    name: '김진학',
    company: '율림건설㈜',
    position: '전무이사',
    memberType: '',
    field: '시행/시공',
    department: '융합분과',
    phone: '010-3545-5355',
    email: 'jinhakk12@gmail.com',
    intro: '',
  },
  {
    id: '26013',
    name: '김태윤',
    company: '㈜아이엔에스시스템',
    position: '대표이사',
    memberType: '',
    field: '전문건설',
    department: '개발분과',
    phone: '010-2685-0651',
    email: 'ins2309@naver.com',
    intro: '',
  },
  {
    id: '26014',
    name: '김태형',
    company: 'GS건설',
    position: '상무',
    memberType: '정회원',
    field: '시행/시공',
    department: '개발분과',
    phone: '010-2221-5789',
    email: 'thkim6@gsenc.com',
    intro: '',
  },
  {
    id: '26015',
    name: '김태훈',
    company: '우암건설㈜',
    position: '사업본부장',
    memberType: '',
    field: '시공',
    department: '도시분과',
    phone: '010-5430-0430',
    email: 'kimth@wooamcon.co.kr',
    intro: '',
  },
  {
    id: '26016',
    name: '김평',
    company: '주식회사 신안디앤씨',
    position: '대표이사',
    memberType: '',
    field: '분양대행',
    department: '도시분과',
    phone: '010-7437-7474',
    email: 'shinan7373@naver.com',
    intro: '',
  },
  {
    id: '26017',
    name: '김학성',
    company: '㈜성현이앤씨',
    position: '대표이사',
    memberType: '',
    field: '전문건설',
    department: '개발분과',
    phone: '010-9251-9005',
    email: 'asadap@naver.com',
    intro: '',
  },
  {
    id: '26018',
    name: '남은오',
    company: '㈜태정종합건설',
    position: '대표이사',
    memberType: '',
    field: '시공',
    department: '창조분과',
    phone: '010-2608-3654',
    email: 'tj5136@hanmail.net',
    intro: '',
  },
  {
    id: '26019',
    name: '노거희',
    company: '주식회사 마리디앤씨',
    position: '대표이사',
    memberType: '',
    field: '시행',
    department: '융합분과',
    phone: '010-4282-9550',
    email: 'nhhoux@naver.com',
    intro: '',
  },
  {
    id: '26020',
    name: '노원수',
    company: '㈜에이치엠',
    position: '전무',
    memberType: '정회원',
    field: '시행',
    department: '도시분과',
    phone: '010-4174-1470',
    email: 'enemy9980@naver.com',
    intro: '',
  },
  {
    id: '26021',
    name: '도종광',
    company: '한국인프라컨설팅',
    position: '부문대표',
    memberType: '',
    field: '시행겸업',
    department: '융합분과',
    phone: '010-9155-7314',
    email: 'jkdoh@kifas.co.kr',
    intro: '',
  },
  {
    id: '26022',
    name: '류권',
    company: '주식회사 대유건설',
    position: '대표이사',
    memberType: '',
    field: '시공',
    department: '도시분과',
    phone: '010-9766-8283',
    email: 'daeyoo@isit.kr',
    intro: '',
  },
  {
    id: '26023',
    name: '맹성호',
    company: '에이앤유디자인그룹 건축사사무소㈜',
    position: '부사장',
    memberType: '준회원',
    field: '설계/감리',
    department: '창조분과',
    phone: '010-6243-2342',
    email: 'shmaeng@anudg.com',
    intro: '',
  },
  {
    id: '26024',
    name: '박명식',
    company: '테마종합건설',
    position: '이사',
    memberType: '',
    field: '시행/시공',
    department: '개발분과',
    phone: '010-3389-9428',
    email: 'pamosik@hanmail.net',
    intro: '',
  },
  {
    id: '26025',
    name: '박승옥',
    company: '육송㈜',
    position: '회장',
    memberType: '',
    field: '전문건설',
    department: '융합분과',
    phone: '010-5211-2407',
    email: 'ceo@yooksong.com',
    intro: '',
  },
  {
    id: '26026',
    name: '박옥진',
    company: '마롬커뮤니케이션',
    position: '기획이사',
    memberType: '',
    field: '기타',
    department: '융합분과',
    phone: '010-8829-7616',
    email: 'okjin0070@naver.com',
    intro: '',
  },
  {
    id: '26027',
    name: '박준형',
    company: '국토교통부',
    position: '토지정책관',
    memberType: '',
    field: '공공기관',
    department: '창조분과',
    phone: '010-2263-2274',
    email: 'jjun0104@gmail.com',
    intro: '',
  },
  {
    id: '26028',
    name: '박홍주',
    company: '㈜씨에이파트너스',
    position: '대표이사',
    memberType: '준회원',
    field: '시행',
    department: '창조분과',
    phone: '010-3470-8421',
    email: 'jesse.park@casp.co.kr',
    intro: '',
  },
  {
    id: '26029',
    name: '방유진',
    company: 'BNY Mellon 투자자문 ㈜',
    position: '대표이사',
    memberType: '',
    field: '금융',
    department: '창조분과',
    phone: '010-4168-8604',
    email: 'eugene.bang@bny.com',
    intro: '',
  },
  {
    id: '26030',
    name: '백승준',
    company: '㈜원진엔지니어링',
    position: '대표이사',
    memberType: '',
    field: '전문건설',
    department: '창조분과',
    phone: '010-2393-1361',
    email: 'sj.baek@wonjhin.com',
    intro: '',
  },
  {
    id: '26031',
    name: '송철한',
    company: '㈜스페이스에코',
    position: '대표이사',
    memberType: '',
    field: '전문건설',
    department: '도시분과',
    phone: '010-9107-7948',
    email: 'echo@space-echo.com',
    intro: '',
  },
  {
    id: '26032',
    name: '심동한',
    company: '우미건설㈜',
    position: '상무',
    memberType: '정회원',
    field: '시행/시공',
    department: '개발분과',
    phone: '010-8780-0075',
    email: 'shimpson75@naver.com',
    intro: '',
  },
  {
    id: '26033',
    name: '안대호',
    company: '㈜나우동인건축사사무소',
    position: '대표',
    memberType: '',
    field: '설계/감리',
    department: '개발분과',
    phone: '010-4559-4453',
    email: 'andaeho@nowarch.com',
    intro: '',
  },
  {
    id: '26034',
    name: '양상화',
    company: '주식회사 개성건설',
    position: '상무이사',
    memberType: '정회원',
    field: '시행/시공',
    department: '도시분과',
    phone: '010-3713-0930',
    email: 'ys.yang@kae-sung.co.kr',
    intro: '',
  },
  {
    id: '26035',
    name: '오동진',
    company: '대신증권',
    position: '본부장',
    memberType: '',
    field: '금융',
    department: '도시분과',
    phone: '010-9748-2788',
    email: 'odong88@hanmail.net',
    intro: '',
  },
  {
    id: '26036',
    name: '오재용',
    company: '한양증권',
    position: '상무',
    memberType: '',
    field: '금융',
    department: '도시분과',
    phone: '010-3788-7736',
    email: 'dksldi80@naver.com',
    intro: '',
  },
  {
    id: '26037',
    name: '우정혁',
    company: '주식회사 시너지로직고',
    position: '부사장',
    memberType: '준회원',
    field: '시행',
    department: '창조분과',
    phone: '010-6333-1134',
    email: 'fururu79@gmail.com',
    intro: '',
  },
  {
    id: '26038',
    name: '이동걸',
    company: '신영증권',
    position: '이사대우',
    memberType: '',
    field: '금융',
    department: '개발분과',
    phone: '010-8865-9031',
    email: 'don.dg.lee@gmail.com',
    intro: '',
  },
  {
    id: '26039',
    name: '이명화',
    company: '㈜디자인그룹꼬시나',
    position: '대표',
    memberType: '',
    field: '시행겸업',
    department: '창조분과',
    phone: '010-7339-2607',
    email: 'robokap@hanmail.net',
    intro: '',
  },
  {
    id: '26040',
    name: '이원석',
    company: '㈜림코',
    position: '대표이사',
    memberType: '',
    field: '시행겸업',
    department: '도시분과',
    phone: '010-8979-3485',
    email: 'jmlee@rimco.co.kr',
    intro: '',
  },
  {
    id: '26041',
    name: '이은',
    company: '주식회사 엠비앤홀딩스',
    position: '전무',
    memberType: '정회원',
    field: '시행겸업',
    department: '개발분과',
    phone: '010-9702-6566',
    email: 'eun.lee@mbnholdings.co.kr',
    intro: '',
  },
  {
    id: '26042',
    name: '이정혁',
    company: '로고스투자자문㈜',
    position: '상무',
    memberType: '',
    field: '금융',
    department: '융합분과',
    phone: '010-2998-7727',
    email: 'kent7727@logosfn.com',
    intro: '',
  },
  {
    id: '26043',
    name: '이종원',
    company: '허브자산운용 주식회사',
    position: '상무',
    memberType: '준회원',
    field: '금융',
    department: '개발분과',
    phone: '010-8916-7950',
    email: 'jwonlee@hubasset.co.kr',
    intro: '',
  },
  {
    id: '26044',
    name: '이충한',
    company: '신성연립소규모재건축 정비사업조합',
    position: '조합장',
    memberType: '',
    field: '시행',
    department: '융합분과',
    phone: '010-5540-0926',
    email: 'sdoong@hanmail.net',
    intro: '',
  },
  {
    id: '26045',
    name: '장영은',
    company: '씨케이프라퍼티',
    position: '대표',
    memberType: '',
    field: '시행',
    department: '개발분과',
    phone: '010-5252-8999',
    email: 'scarlet21@hanmail.net',
    intro: '',
  },
  {
    id: '26046',
    name: '장용서',
    company: '㈜서정인터내셔날',
    position: '대표이사',
    memberType: '',
    field: '기타',
    department: '창조분과',
    phone: '010-8906-3742',
    email: 'yschang@sj-intl.com',
    intro: '',
  },
  {
    id: '26047',
    name: '전정은',
    company: '㈜다원앤컴퍼니',
    position: '전무',
    memberType: '준회원',
    field: '전문건설',
    department: '융합분과',
    phone: '010-3662-0225',
    email: 'jejeon@dawon.com',
    intro: '',
  },
  {
    id: '26048',
    name: '정용재',
    company: '삼성증권',
    position: '팀장/이사',
    memberType: '준회원',
    field: '금융',
    department: '창조분과',
    phone: '010-6543-0730',
    email: 'yongjae.chung@samsung.com',
    intro: '',
  },
  {
    id: '26049',
    name: '정지융',
    company: '㈜위더스',
    position: '사장',
    memberType: '',
    field: '시행겸업',
    department: '창조분과',
    phone: '010-9116-7059',
    email: 'cm3004@daum.net',
    intro: '',
  },
  {
    id: '26050',
    name: '정태희',
    company: '주식회사 바이오피아',
    position: '이사',
    memberType: '정회원',
    field: '시행',
    department: '창조분과',
    phone: '010-8600-8293',
    email: 'taeheejung1977@gmail.com',
    intro: '',
  },
  {
    id: '26051',
    name: '정호경',
    company: '㈜삼건사',
    position: '대표이사',
    memberType: '준회원',
    field: '시공',
    department: '창조분과',
    phone: '010-9115-6775',
    email: 'jhok9093@gmail.com',
    intro: '',
  },
  {
    id: '26052',
    name: '조민호',
    company: '㈜원포올디앤씨',
    position: '대표이사',
    memberType: '준회원',
    field: '분양대행',
    department: '융합분과',
    phone: '010-9109-9239',
    email: 'cmh1981c@nate.com',
    intro: '',
  },
  {
    id: '26053',
    name: '조일훈',
    company: 'JMC파트너스',
    position: '대표',
    memberType: '',
    field: '시행겸업',
    department: '융합분과',
    phone: '010-6560-0091',
    email: 'joil0091@naver.com',
    intro: '',
  },
  {
    id: '26054',
    name: '채지원',
    company: '루시아홀딩스㈜',
    position: '회장',
    memberType: '정회원',
    field: '시행',
    department: '개발분과',
    phone: '010-2915-8880',
    email: 'ceo@luxiaholdings.com',
    intro: '',
  },
  {
    id: '26055',
    name: '최상권',
    company: '하우스 테일러 공인중개사사무소',
    position: '대표',
    memberType: '',
    field: '시행겸업',
    department: '개발분과',
    phone: '010-4127-0505',
    email: 'choisg85@naver.com',
    intro: '',
  },
  {
    id: '26056',
    name: '최재진',
    company: 'HL디앤아이 한라',
    position: '팀장',
    memberType: '정회원',
    field: '시공',
    department: '융합분과',
    phone: '010-6607-2994',
    email: 'jaejin.choi@hlcompany.com',
    intro: '',
  },
  {
    id: '26057',
    name: '최태진',
    company: '서초세무서',
    position: '조사팀장',
    memberType: '',
    field: '공공기관',
    department: '융합분과',
    phone: '010-5298-9402',
    email: 'a01052989402@gmail.com',
    intro: '',
  },
  {
    id: '26058',
    name: '태원출',
    company: '삼성물산㈜',
    position: '팀장',
    memberType: '정회원',
    field: '시행/시공',
    department: '창조분과',
    phone: '010-3320-0063',
    email: 'tae510@naver.com',
    intro: '',
  },
  {
    id: '26059',
    name: '함경자',
    company: '㈜에스알비애드',
    position: '부사장',
    memberType: '준회원',
    field: '기타',
    department: '도시분과',
    phone: '010-2287-5511',
    email: 'luna5511@naver.com',
    intro: '',
  },
  {
    id: '26060',
    name: '홍창표',
    company: '유진투자증권',
    position: '담당',
    memberType: '준회원',
    field: '금융',
    department: '융합분과',
    phone: '010-9543-4445',
    email: 'hcpwin@naver.com',
    intro: '',
  },
];

const attendanceLookupData = [
  {
    id: "26060",
    name: "홍창표",
    company: "유진투자증권",
    position: "담당",
    department: "융합분과",
    attendanceRate: 100,
    summary: {
      present: 3,
      late: 0,
      earlyLeave: 0,
      absent: 0
    },
    weekly: [
      { week: "1주차", status: "출석", topic: "입학식" },
      { week: "2주차", status: "출석", topic: "부동산트랜드와 주택 정책" },
      { week: "3주차", status: "출석", topic: "부동산 프로젝트 리츠 사업" }
    ]
  },
  {
    id: "26001",
    name: "김구현",
    company: "케이알산업",
    position: "상무",
    department: "개발분과",
    attendanceRate: 100,
    summary: {
      present: 3,
      late: 0,
      earlyLeave: 0,
      absent: 0
    },
    weekly: [
      { week: "1주차", status: "출석", topic: "입학식" },
      { week: "2주차", status: "출석", topic: "부동산트랜드와 주택 정책" },
      { week: "3주차", status: "출석", topic: "부동산 프로젝트 리츠 사업" }
    ]
  },
  {
    id: "26002",
    name: "김기현",
    company: "코람코자산신탁",
    position: "이사",
    department: "융합분과",
    attendanceRate: 66.7,
    summary: {
      present: 2,
      late: 1,
      earlyLeave: 0,
      absent: 0
    },
    weekly: [
      { week: "1주차", status: "출석", topic: "입학식" },
      { week: "2주차", status: "지각", topic: "부동산트랜드와 주택 정책" },
      { week: "3주차", status: "출석", topic: "부동산 프로젝트 리츠 사업" }
    ]
  },
  {
    id: "26003",
    name: "김선철",
    company: "㈜나산종합건축사사무소",
    position: "사장",
    department: "도시분과",
    attendanceRate: 33.3,
    summary: {
      present: 1,
      late: 0,
      earlyLeave: 0,
      absent: 2
    },
    weekly: [
      { week: "1주차", status: "결석", topic: "입학식" },
      { week: "2주차", status: "출석", topic: "부동산트랜드와 주택 정책" },
      { week: "3주차", status: "결석", topic: "부동산 프로젝트 리츠 사업" }
    ]
  }
];

const notices = [
  {
    title: "4월 정기 모임 안내",
    date: "2026-04-05",
    content: "4월 정기 모임은 4월 5일 오후 7시에 진행됩니다."
  },
  {
    title: "원우수첩 정보 업데이트 요청",
    date: "2026-04-02",
    content: "회사명, 직책, 연락처 변경사항이 있는 분들은 운영진에게 알려주세요."
  }
];

const curriculum = [
  {
    week: "1주차",
    date: "03월 16일",
    title: "입학식",
    speaker: "KODA 사무국",
    organization: "입학식"
  },
  {
    week: "2주차",
    date: "03월 23일",
    title: "부동산트랜드와 주택 정책",
    speaker: "진희선",
    organization: "연세대 도시공학과 특임교수"
  },
  {
    week: "3주차",
    date: "03월 30일",
    title: "부동산 프로젝트 리츠 사업",
    speaker: "김승범",
    organization: "국토교통부 과장"
  },
  {
    week: "4주차",
    date: "04월 06일",
    title: "특강(디벨로퍼의 상상력)",
    speaker: "문주현",
    organization: "한국부동산개발협회 명예회장 / 엠디엠그룹 회장"
  },
  {
    week: "5주차",
    date: "04월 13일",
    title: "인구와 부, 인구학 / 부동산 PF시장 현황과 위기에 대한 정부정책",
    speaker: "고우림 / 이병훈",
    organization: "서울대 보건대학원 교수 / 대한주택건설협회 부회장"
  }
];

const gallery = [
  {
    title: "입학식 현장",
    date: "2026-03-20",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=800&q=80"
  },
  {
    title: "첫 네트워킹",
    date: "2026-03-20",
    image: "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=800&q=80"
  }
];

const boardPosts = [
  {
    title: "자기소개 글 남겨주세요",
    author: "운영진",
    date: "2026-04-01",
    content: "간단한 자기소개와 관심 분야를 자유롭게 남겨주세요."
  }
];